../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_B.arpa -ppl ./data/task3_test_segmented_B.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_W.arpa -ppl ./data/task3_test_segmented_W.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_T.arpa -ppl ./data/task3_test_segmented_T.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_S2.arpa -ppl ./data/task3_test_segmented_S2.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_S3.arpa -ppl ./data/task3_test_segmented_S3.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_S4.arpa -ppl ./data/task3_test_segmented_S4.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_S5.arpa -ppl ./data/task3_test_segmented_S5.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_P2.arpa -ppl ./data/task3_test_segmented_P2.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_P3.arpa -ppl ./data/task3_test_segmented_P3.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_P4.arpa -ppl ./data/task3_test_segmented_P4.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_P5.arpa -ppl ./data/task3_test_segmented_P5.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_PW.arpa -ppl ./data/task3_test_segmented_PW.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_SW.arpa -ppl ./data/task3_test_segmented_SW.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o2_PSW.arpa -ppl ./data/task3_test_segmented_PSW.txt -order 2 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_W.arpa -ppl ./data/task3_test_segmented_W.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_T.arpa -ppl ./data/task3_test_segmented_T.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_S2.arpa -ppl ./data/task3_test_segmented_S2.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_S3.arpa -ppl ./data/task3_test_segmented_S3.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_S4.arpa -ppl ./data/task3_test_segmented_S4.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_S5.arpa -ppl ./data/task3_test_segmented_S5.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_P2.arpa -ppl ./data/task3_test_segmented_P2.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_P3.arpa -ppl ./data/task3_test_segmented_P3.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_P4.arpa -ppl ./data/task3_test_segmented_P4.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_P5.arpa -ppl ./data/task3_test_segmented_P5.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_PW.arpa -ppl ./data/task3_test_segmented_PW.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_SW.arpa -ppl ./data/task3_test_segmented_SW.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o3_PSW.arpa -ppl ./data/task3_test_segmented_PSW.txt -order 3 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_B.arpa -ppl ./data/task3_test_segmented_B.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_W.arpa -ppl ./data/task3_test_segmented_W.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_T.arpa -ppl ./data/task3_test_segmented_T.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_S2.arpa -ppl ./data/task3_test_segmented_S2.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_S3.arpa -ppl ./data/task3_test_segmented_S3.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_S4.arpa -ppl ./data/task3_test_segmented_S4.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_S5.arpa -ppl ./data/task3_test_segmented_S5.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_P2.arpa -ppl ./data/task3_test_segmented_P2.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_P3.arpa -ppl ./data/task3_test_segmented_P3.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_P4.arpa -ppl ./data/task3_test_segmented_P4.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_P5.arpa -ppl ./data/task3_test_segmented_P5.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_PW.arpa -ppl ./data/task3_test_segmented_PW.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_SW.arpa -ppl ./data/task3_test_segmented_SW.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o4_PSW.arpa -ppl ./data/task3_test_segmented_PSW.txt -order 4 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_B.arpa -ppl ./data/task3_test_segmented_B.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_W.arpa -ppl ./data/task3_test_segmented_W.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_T.arpa -ppl ./data/task3_test_segmented_T.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_S2.arpa -ppl ./data/task3_test_segmented_S2.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_S3.arpa -ppl ./data/task3_test_segmented_S3.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_S4.arpa -ppl ./data/task3_test_segmented_S4.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_S5.arpa -ppl ./data/task3_test_segmented_S5.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_P2.arpa -ppl ./data/task3_test_segmented_P2.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_P3.arpa -ppl ./data/task3_test_segmented_P3.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_P4.arpa -ppl ./data/task3_test_segmented_P4.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_P5.arpa -ppl ./data/task3_test_segmented_P5.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_PW.arpa -ppl ./data/task3_test_segmented_PW.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_SW.arpa -ppl ./data/task3_test_segmented_SW.txt -order 5 -unk >> perplexity.log
../srilm/lm/bin/i686-m64/ngram -lm ./models/kenlm_o5_PSW.arpa -ppl ./data/task3_test_segmented_PSW.txt -order 5 -unk >> perplexity.log