# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_W.txt --features="W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_B.txt --features="B" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_T.txt --features="T" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S2.txt --features="S2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S3.txt --features="S3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S4.txt --features="S4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S5.txt --features="S5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P2.txt --features="P2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P3.txt --features="P3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P4.txt --features="P4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P5.txt --features="P5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S2.txt --features="S2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S3.txt --features="S3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S4.txt --features="S4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S5.txt --features="S5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_PW.txt --features="PW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_SW.txt --features="SW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
# python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_PSW.txt --features="PSW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_B_W.txt --features="B W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_T_W.txt --features="T W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S2_W.txt --features="S2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S3_W.txt --features="S3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S4_W.txt --features="S4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S5_W.txt --features="S5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P2_W.txt --features="P2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P3_W.txt --features="P3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P4_W.txt --features="P4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_P5_W.txt --features="P5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S2_W.txt --features="S2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S3_W.txt --features="S3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S4_W.txt --features="S4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_S5_W.txt --features="S5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_PW_W.txt --features="PW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_SW_W.txt --features="SW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_train_segmented.txt --output=data/task3_train_segmented_PSW_W.txt --features="PSW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_W.txt --features="W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_B.txt --features="B" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_T.txt --features="T" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S2.txt --features="S2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S3.txt --features="S3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S4.txt --features="S4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S5.txt --features="S5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P2.txt --features="P2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P3.txt --features="P3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P4.txt --features="P4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P5.txt --features="P5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S2.txt --features="S2" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S3.txt --features="S3" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S4.txt --features="S4" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S5.txt --features="S5" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_PW.txt --features="PW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_SW.txt --features="SW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_PSW.txt --features="PSW" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_B_W.txt --features="B W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_T_W.txt --features="T W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S2_W.txt --features="S2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S3_W.txt --features="S3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S4_W.txt --features="S4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S5_W.txt --features="S5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P2_W.txt --features="P2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P3_W.txt --features="P3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P4_W.txt --features="P4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_P5_W.txt --features="P5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S2_W.txt --features="S2 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S3_W.txt --features="S3 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S4_W.txt --features="S4 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_S5_W.txt --features="S5 W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_PW_W.txt --features="PW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_SW_W.txt --features="SW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt
python preprocessing/preprocess_file.py --input=data/task3_test_segmented.txt --output=data/task3_test_segmented_PSW_W.txt --features="PSW W" --supertags=data/NLP/supertags.txt --prefixes=data/NLP/super_prefiksy.txt --bases=data/NLP/superbazy.txt --suffixes=data/NLP/sufiksy10K.txt --vocabulary=data/NLP/words1Kplus.txt